<?php

namespace AppBundle\Repository;

/**
 * PhoneNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
